### ISSUE TITLE
No ___(un)install() needed in Process modules

### ISSUE THREAD

**Issue by LostKobrakai** [benbyford/PW-intermediate-modules#1]
ProcessPages are automatically created by the "page" config options you can see here: https://github.com/ryancramerdesign/ProcessHello/blob/master/ProcessHello.info.php

**Comment by benbyford** [comment]
not sure what you mean here sorry

**Comment by LostKobrakai** [comment]
The install() and uninstall() method here are not needed, because processwire can automatically create/delete that page if you use the correct module config. https://github.com/benbyford/PW-intermediate-modules/blob/master/ProcessSimpleAdminPage/ProcessSimpleAdminPage.module

You just need to either not define an install/uninstall method or call parent::___install() / parent::uninstall() in those defined methods.

**Comment by benbyford** [comment]
sweet will give that a go. I might make a note that thats the case in the module but not implemement as thats not a usual design pattern for other modules that need to make pages–i'm using these modules to show spepcific things within PW.
